

x-airflow-env: &airflow-env
  # Executor
  AIRFLOW__CORE__EXECUTOR: LocalExecutor

  # Metadata DB (RDS)
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}

  # Core settings
  AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"

  # API auth
  AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session

  # Install extra packages 
  _PIP_ADDITIONAL_REQUIREMENTS: >
    apache-airflow-providers-postgres
    python-dotenv
    dbt-postgres==1.7.4

  AIRFLOW_UID: ${AIRFLOW_UID:-50000}

x-airflow-common: &airflow-common
  image: apache/airflow:2.9.1-python3.10
  env_file:
    - .env
  environment:
    <<: *airflow-env

  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./data:/opt/airflow/data
    - ./sql:/opt/airflow/sql
    - ./scripts:/opt/airflow/scripts
    - ./dbt_project:/opt/airflow/dbt_project
    - ./dbt_project/ny_taxi_dbt/.dbt:/opt/airflow/.dbt

  user: "${AIRFLOW_UID:-50000}:0"

services:

  #########################################
  # Airflow DB Init
  #########################################
  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command: >
      -c "
      airflow db migrate &&
      airflow users create --username airflow --password airflow --firstname Admin --lastname User --role Admin --email admin@example.com || true
      "
    restart: "no"

  #########################################
  # Webserver
  #########################################
  airflow-webserver:
    <<: *airflow-common
    command: webserver
    environment:
      <<: *airflow-env
      # Increase gunicorn master timeout to allow time for package installation
      AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT: "300"
    ports:
      - "8080:8080"
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      start_period: 300s
      retries: 10

  #########################################
  # Scheduler
  #########################################
  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    restart: unless-stopped

  